// Copyright (c) Contributors to the SPK project.
// SPDX-License-Identifier: Apache-2.0

//! Environment variable operations for spenv.
//!
//! This module defines a minimal subset of the SPK `EnvOp` machinery
//! tailored for `.spenv.yaml` files and startup script generation.

use serde::{Deserialize, Serialize};

#[cfg(test)]
#[path = "./environment_test.rs"]
mod environment_test;

/// Environment variable operation.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(untagged)]
pub enum EnvOp {
    Set(SetEnv),
    Prepend(PrependEnv),
    Append(AppendEnv),
    Comment(CommentEnv),
    Priority(PriorityEnv),
}

/// Set an environment variable to a specific value.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct SetEnv {
    pub set: String,
    pub value: String,
}

/// Prepend a value to an environment variable.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PrependEnv {
    pub prepend: String,
    pub value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub separator: Option<String>,
}

/// Append a value to an environment variable.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct AppendEnv {
    pub append: String,
    pub value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub separator: Option<String>,
}

/// Comment to include in generated scripts.
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct CommentEnv {
    pub comment: String,
}

/// Priority hint for startup script ordering (0-99, lower runs earlier).
#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct PriorityEnv {
    pub priority: u8,
}

impl EnvOp {
    /// Get default separator based on platform.
    fn default_separator() -> &'static str {
        #[cfg(windows)]
        {
            ";"
        }
        #[cfg(not(windows))]
        {
            ":"
        }
    }

    /// Generate bash source code for this operation.
    pub fn bash_source(&self) -> String {
        match self {
            EnvOp::Set(s) => {
                format!("export {}=\"{}\"", s.set, escape_value(&s.value))
            }
            EnvOp::Prepend(p) => {
                let sep = p.separator.as_deref().unwrap_or(EnvOp::default_separator());
                format!(
                    "export {}=\"{}{}${{{}}}\"",
                    p.prepend,
                    escape_value(&p.value),
                    sep,
                    p.prepend,
                )
            }
            EnvOp::Append(a) => {
                let sep = a.separator.as_deref().unwrap_or(EnvOp::default_separator());
                format!(
                    "export {}=\"${{{}}}{}{}\"",
                    a.append,
                    a.append,
                    sep,
                    escape_value(&a.value),
                )
            }
            EnvOp::Comment(c) => {
                format!("# {}", c.comment)
            }
            EnvOp::Priority(_) => {
                // Priority affects filename, not script content.
                String::new()
            }
        }
    }
}

/// Escape value for safe use in shell scripts.
fn escape_value(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
}

/// Get priority from environment operations.
///
/// Returns the first explicit priority operation if present,
/// otherwise a default of 50.
pub fn get_priority(ops: &[EnvOp]) -> u8 {
    ops.iter()
        .find_map(|op| match op {
            EnvOp::Priority(p) => Some(p.priority),
            _ => None,
        })
        .unwrap_or(50)
}

/// Generate a bash startup script from a list of operations.
pub fn generate_startup_script(ops: &[EnvOp]) -> String {
    let mut script = String::new();
    script.push_str("#!/bin/bash\n");
    script.push_str("# Generated by spenv\n\n");

    for op in ops {
        let line = op.bash_source();
        if !line.is_empty() {
            script.push_str(&line);
            script.push('\n');
        }
    }

    script
}
